### PR TITLE
Activity

### PR DESCRIPTION
**Pull request by khanhlyvu30**
TAG: https://edu-redmine.sun-asterisk.vn/issues/27387?issue_count=27&issue_position=12&next_issue_id=27386&prev_issue_id=27388

WHAT: can see your and following's activities

image

### CODE REVIEW

**Review by TranVanPine — APPROVED** [review]

**Review by NguyenDungB — APPROVED** [review]

**Comment by khanhlyvu30** [comment]
ready

**Review by thaodtd-0665 — COMMENTED** [review]
pull đang có 2 commit

**Comment by khanhlyvu30** [comment]
ready

**Review by thaodtd-0665 — COMMENTED** [review]
commit bị đè lên commit trước đó rồi em

**Comment by khanhlyvu30** [comment]
ready

**Review by thaodtd-0665 — APPROVED** [review]

**Pull request merged**
