### PR TITLE
Create test model and test view for "Category"

### PR DESCRIPTION
**Pull request by TranVanPine**
TAG: https://edu-redmine.sun-asterisk.vn/issues/29378
WHAT: Create test model and test view for "Category"
image

### CODE REVIEW

**Comment by TranVanPine** [comment]
ready

**Comment by TranVanPine** [comment]
ready

**Review by thaodtd-0665 — COMMENTED** [review]
kết quả test chưa đúng nhé, run rồi attachment nha

**Comment by TranVanPine** [comment]
ready

**Review by thaodtd-0665 — APPROVED** [review]

**Pull request merged**
